ALTER TABLE users
ADD COLUMN full_name VARCHAR(100) NOT NULL DEFAULT 'CollabFlow User';

ALTER TABLE users
ADD COLUMN role VARCHAR(30) NOT NULL DEFAULT 'USER';

ALTER TABLE users
ADD COLUMN updated_at TIMESTAMP;